chore: began creating the search by Ings screen
danielemonaca/barbeat pull request #20
Opened 2022-12-02 03:47 UTC by stefanomusicman

# Description of the problem
began creating the search by Ingredients screen

## How does it solve the problem
different parts have been split in order to keep code lean, following same patterns and procedures as usual

# References (also the Jira ticket)
BAR-46

# Checklist:

- [ ] I re-reviewed the Jira ticket now to make sure 
- [ ] My code follows the style guidelines of this project & of Dart
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have wrote some documentation if I changed a big behavior of the code
- [ ] My changes generate no new warnings/and if they do, I described them to the team
- [ ] I have added tests that prove my fix is effective or that my feature works if I worked on a logic class/function
- [ ] New and existing unit and integration tests pass locally with my changes

2022-12-03 05:19 UTC, stefanomusicman commented
![Untitled](https://user-images.githubusercontent.com/94554115/205425286-17fdc237-b232-47b6-a4f7-b73c73b949fb.png)
![Untitled1](https://user-images.githubusercontent.com/94554115/205425287-ae511bde-5b42-4835-8c90-97fc55a53047.png)

2022-12-03 14:28 UTC, danielemonaca commented
Wow, it's impressive really!

As the PR is not set in `ready for review` I didn't do a full review, but here are some quick things I found:

- The `rectangle.svg` is a duplicate of `white_bottom_part.svg` that was used in the intros, you could think about extracting that
- You access the page by clicking the `Search By Ingredients` button in the home, not the search bar
- When you click the search bar/plus icon right now it just pushes the keyboard, the requirements from when you click the bottom panel are the following:
    1. Expands the panel( not to the totally top, but like the same height on you could do it manually)
    2. After that, you can pull up the keyboard, which should not push the design as it does now, but would go on top of the design.


Let me know when you have questions

2022-12-08 03:09 UTC, danielemonaca commented on lib/ui/screens/home/discover_new_ones.dart
> +    // final data = gridData;
Do we still need this comment?

2022-12-08 03:13 UTC, danielemonaca commented on lib/ui/screens/searchByIngs/panel_widget.dart
> +            color: const Color(0xFFD9D9D9),
What color is that? 😆

2022-12-08 03:16 UTC, danielemonaca commented on lib/ui/screens/searchByIngs/searchByIngs_background.dart
> +      // bottom: -4,
Can we remove this?

2022-12-08 03:16 UTC, danielemonaca commented on lib/ui/screens/searchByIngs/searchByIngs_background.dart
> +      // top: 5,
Can we remove this?

2022-12-08 03:16 UTC, danielemonaca commented on lib/ui/screens/searchByIngs/searchByIngs_main.dart
> +              NoIngsPic(size: size), // TODO: render conditionally***
Nice TODO comment here

2022-12-08 03:21 UTC, danielemonaca commented on pubspec.yaml
> +  flutter_keyboard_visibility: ^5.4.0
Fun fact:
I thought that adding so many packages would hurt the final app's size, but then I saw this:

> Dart comes with a Tree Shaker algorithm that will remove all unused code in release mode, reducing the size of your app to only the minimum.
> 
> So there's no real comparison with java and the jar size. Only the code you use will be added to your application.

2022-12-08 03:26 UTC, danielemonaca commented
![image](https://user-images.githubusercontent.com/47630631/206349295-cad36cb0-134e-42cf-bb0e-b966099592f6.png)
I think the text has some mismatch in terms of font weight, could you try to re-adjust it?

2022-12-08 03:31 UTC, danielemonaca commented
![image](https://user-images.githubusercontent.com/47630631/206349556-7b83eec4-cbfd-4421-ab8b-afced8a25c0a.png)
The background is not white but is `#FAF8F2`

If you now try and fetch the latest main branch, you will have available this code here:
```
import 'package:barbeat/common_libs.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:simple_shadow/simple_shadow.dart';

Widget buildWhiteBottomPart(Size size, {double? height, Color? color}) {
  const whiteBottomPart = 'assets/introImages/white_bottom_part.svg';
  const shadowWhiteBottomPartColor = Color(0xFFC7C5C1);
  return Positioned(
    bottom: -40,
    child: SizedBox(
      width: size.width,
      height: size.height * (height ?? 0.65),
      child: SimpleShadow(
          opacity: 0.40,
          color: shadowWhiteBottomPartColor,
          offset: const Offset(-10, -10),
          sigma: 7,
          child: SvgPicture.asset(
            whiteBottomPart,
            fit: BoxFit.cover,
            color: color ?? Colors.white,
          )),
    ),
  );
}
```

so you can just replace your background with something like
`final Color _colorForArchBackground = const Color(0xFFFAF8F2);`
...
`buildWhiteBottomPart(size, height: 0.60, color: _colorForArchBackground)`

2022-12-08 03:38 UTC, danielemonaca commented
I have just seen something that we can improve out of the search field, so I created a ticket for it for the next sprints: https://unboolean.atlassian.net/jira/software/projects/BAR/boards/3/backlog?selectedIssue=BAR-83

2022-12-08 03:44 UTC, danielemonaca requested changes
Some UI changes are needed, but functionality-wise, it's incredible!!

2022-12-10 05:47 UTC, stefanomusicman commented on pubspec.yaml
> +  flutter_keyboard_visibility: ^5.4.0
good to know!

2022-12-10 06:38 UTC, stefanomusicman commented on lib/ui/screens/home/discover_new_ones.dart
> +    // final data = gridData;
nope, i removed it

2022-12-10 09:26 UTC, danielemonaca commented on analysis_options.yaml
> +    file_names: false
What is this?

2022-12-10 09:34 UTC, danielemonaca commented
I think there is an issue with the most popular container? 
![image](https://user-images.githubusercontent.com/47630631/206843921-30042e38-9c10-412b-bf3f-2492741b7ffd.png)

2022-12-10 15:00 UTC, danielemonaca approved these changes
Very very nice

2022-12-10 21:21 UTC, merged